default:
  image: gcc:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build
  - test

build:
  tags:
    - linux-docker
  script:
    - make

test:
  tags:
    - linux
  script:
    - make test
