default:
  image: registry.rivercry.com/arifhasanic/cmake/cmake:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - test

test:
  stage: test
  tags:
    - linux-docker
  script:    
    - cd enigma_c
    - mkdir build
    - cd build
    - cmake -DENABLE_COVERAGE=ON ..
    - make
    - make test
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}/enigma_c --exclude ${CI_PROJECT_DIR}/enigma_c/test
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: enigma_c/build/coverage.xml