default:
  image: registry.rivercry.com/arifhasanic/cmake/cmake:latest

before_script:
  - apt-get update -qq && apt-get install -y -qq cmake

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - test

test:
  tags:
    - linux-docker
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
