default:
  image: gcc-cmake:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - test

test:
  tags:
    - linux-docker
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
